In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\python312\lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\andre\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: Ignoring invalid distribution ~ (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
import pandas as pd
tabela_final = pd.DataFrame( columns=['Nome', 'Curso', 'Status_Curso'])

In [4]:
tabela_sisu_2020_2 = pd.read_csv('basesdedados/ListagemChamadaRegular_2020-2.csv', sep=';')
tabela_sisu_2020_2.head()

C:\Users\andre\AppData\Local\Temp\ipykernel_16392\3214906904.py:1: DtypeWarning: Columns (19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela_sisu_2020_2 = pd.read_csv('basesdedados/ListagemChamadaRegular_2020-2.csv', sep=';')

,NU_ANO,NU_EDICAO,CO_ETAPA,DS_ETAPA,CO_IES,NO_IES,SIGLA_IES,SG_UF_IES,CO_CAMPUS,NO_CAMPUS,...,NOTA_L_COM_PESO,NOTA_CH_COM_PESO,NOTA_CN_COM_PESO,NOTA_M_COM_PESO,NOTA_R_COM_PESO,NU_NOTA_CANDIDATO,NU_NOTACORTE,NU_CLASSIFICACAO,ST_APROVADO,ST_MATRICULA
0,2020,2,4,1° CHAMADA,688,UNIVERSIDADE ESTADUAL DO SUDOESTE DA BAHIA,UESB,BA,301,Campus de Jequié,...,"2304,8","2304,8","982,4","1897,8",4000,"638,32","601,31",2.0,S,NÃO COMPARECEU
1,2020,2,4,1° CHAMADA,688,UNIVERSIDADE ESTADUAL DO SUDOESTE DA BAHIA,UESB,BA,301,Campus de Jequié,...,"1838,4",1752,"852,8",1320,1800,"420,18","601,31",194.0,N,PENDENTE
2,2020,2,4,1° CHAMADA,688,UNIVERSIDADE ESTADUAL DO SUDOESTE DA BAHIA,UESB,BA,301,Campus de Jequié,...,"1835,6","2022,8",925,"1538,7",3600,"551,23","601,31",55.0,N,PENDENTE
3,2020,2,4,1° CHAMADA,688,UNIVERSIDADE ESTADUAL DO SUDOESTE DA BAHIA,UESB,BA,301,Campus de Jequié,...,"2241,6","1851,2","795,4","1279,8",3100,"514,89","601,31",110.0,N,PENDENTE
4,2020,2,4,1° CHAMADA,688,UNIVERSIDADE ESTADUAL DO SUDOESTE DA BAHIA,UESB,BA,301,Campus de Jequié,...,"1886,4","1459,2","727,2","1157,7",2600,"435,03","578,13",123.0,N,PENDENTE

In [ ]:
nome_view = tabela_sisu_2020_2['NO_INSCRITO']
nome_view

0                   BIANCA STEPHANE DA SILVA
1                  DYANA MENDES GOMES SANTOS
2                  ISADORA SANTIAGO FERREIRA
3          LARA ESTHER MENDES SILVA OLIVEIRA
4                  NAIARA PEREIRA DOS SANTOS
                         ...
814471         IANKA ANALIA BOTELHO DE SOUZA
814472     VINICCIUS MARQUES FERNANDES MOZER
814473             MARIANA MIBIELLI DE SOUZA
814474    MONYKE GABRIELLY FERREIRA FERREIRA
814475           LIVIA BRUNA DE ANDRADE DO O
Name: NO_INSCRITO, Length: 814476, dtype: object

In [ ]:
for i in range(40):
    tabela_final.loc[len(tabela_final)] = {
        'Nome': nome_view[i],
        'Curso' : 'Ainda nada',
        'Status_Curso': 'Cursando'
    }
display(tabela_final)

                                 Nome       Curso Status_Curso
0            BIANCA STEPHANE DA SILVA  Ainda nada     Cursando
1           DYANA MENDES GOMES SANTOS  Ainda nada     Cursando
2           ISADORA SANTIAGO FERREIRA  Ainda nada     Cursando
3   LARA ESTHER MENDES SILVA OLIVEIRA  Ainda nada     Cursando
4           NAIARA PEREIRA DOS SANTOS  Ainda nada     Cursando
5                 GISELE BRITO SANTOS  Ainda nada     Cursando
6             SUZANA DE OLIVEIRA DIAS  Ainda nada     Cursando
7      VITORIA DO NASCIMENTO OLIVEIRA  Ainda nada     Cursando
8            ELIVANIA BASTOS OLIVEIRA  Ainda nada     Cursando
9             IAN VICTTOR SOUZA SILVA  Ainda nada     Cursando
10                ANGELA ASSIS VIEIRA  Ainda nada     Cursando
11        ROSANGELA SOUZA DE OLIVEIRA  Ainda nada     Cursando
12                DANIELLE DOS SANTOS  Ainda nada     Cursando
13   NATIELE SOUZA OLIVEIRA DE ARAGAO  Ainda nada     Cursando
14         DANIELA DA CONCEICAO SILVA  Ainda nada     Cursando
15                ZIARA SANTOS VIEIRA  Ainda nada     Cursando
16             NAIARA DE JESUS SANTOS  Ainda nada     Cursando
17       LUIZ FELIPE FELIX DOS SANTOS  Ainda nada     Cursando
18      AMANDA DOS SANTOS ESCOLASTICO  Ainda nada     Cursando
19            UELMA SANTANA GONCALVES  Ainda nada     Cursando
20            JANETE ANDRADE DA SILVA  Ainda nada     Cursando
21             MANOEL MENDES DA SILVA  Ainda nada     Cursando
22             LUDMILA CASTRO DA CRUZ  Ainda nada     Cursando
23              LARISSA SANTOS PIROPO  Ainda nada     Cursando
24              VALQUIRIA SOUZA NUNES  Ainda nada     Cursando
25          SANDRO ROBERTO DOS SANTOS  Ainda nada     Cursando
26         THAINARA SILVA DE OLIVEIRA  Ainda nada     Cursando
27               ANDRESSA SANTOS DIAS  Ainda nada     Cursando
28            THAMIRES SANTOS ANDRADE  Ainda nada     Cursando
29    MAYANA APARECIDA FERREIRA SOUZA  Ainda nada     Cursando
30               LARISSA SANTOS SILVA  Ainda nada     Cursando
31       QUEZIA DOS SANTOS NASCIMENTO  Ainda nada     Cursando
32            VALDINEY DE JESUS SILVA  Ainda nada     Cursando
33              THAIS SANTOS DE COUTO  Ainda nada     Cursando
34   LUIZA CARLA DE NOVAES NASCIMENTO  Ainda nada     Cursando
35    MARIA DE FATIMA AMORIM DE SOUZA  Ainda nada     Cursando
36             ELISAMA MENDES CORREIA  Ainda nada     Cursando
37          FABRICIA DOS SANTOS TELES  Ainda nada     Cursando
38             BEATRIZ PEREIRA SANTOS  Ainda nada     Cursando
39              REBECA SOUZA DA SILVA  Ainda nada     Cursando

In [ ]:
# Criando uma tabela de teste com nomes que estão na base e outros que não estão